### ISSUE TITLE
Dockerize it

### ISSUE THREAD

**Issue by rogierslag** [orgsync/stoplight-admin#11]
Since I loved both your work on stoplight and stopligh-admin, it was decided to embed these into our own applications. Since adding the spotlight-admin would lead to a bloating application, I extracted it to a separate Docker container. This one is available on Github or directly downloadable from Docker Hub: https://github.com/inventid/stoplight-admin-docker

Let me know when you have any questions or if I messed up with the licensing (currently MIT).

:heart: your work!

**Comment by tfausak** [comment]
Looks great! Stoplight itself is MIT licensed, so you're good to go there.

**Comment by rogierslag** [comment]
Thanks for merging and thanks for the work you have done!
