### ISSUE TITLE
Missing haml files in gem

### ISSUE THREAD

**Issue by machadolab** [orgsync/stoplight-admin#13]
I installed the gem via bundler from rubygems, and the haml files are not included, leading to:

```
Errno::ENOENT at /stoplight/
No such file or directory @ rb_sysopen - /.../gems/stoplight-admin-0.3.0/lib/sinatra/views/index.haml
```

**Comment by mrdziuban** [comment]
I'm also running into this issue. I was able to work around it by referencing this repo and the right tag in my Gemfile, but it would be nice to have this resolved.

@tfausak thoughts on this?

**Comment by tfausak** [comment]
It's weird that we haven't run into this problem. It should be easy enough to add the HAML files to `gem.files` here: https://github.com/orgsync/stoplight-admin/blob/v0.3.0/stoplight-admin.gemspec#L22-L23

**Comment by mrdziuban** [comment]
Just opened a PR to fix this
