### ISSUE TITLE
Consider documenting how to mount admin app in rails

### ISSUE THREAD

**Issue by machadolab** [orgsync/stoplight-admin#14]
I'm not sure I did it correctly, but I ended up creating a mini sinatra app and mounting it in rails.

Example lib/stoplight_admin_app.rb:

```
require 'sinatra/base'
require 'sinatra/stoplight_admin'

class StoplightAdminApp < Sinatra::Base
  register Sinatra::StoplightAdmin

  uri = URI.parse(ENV["REDIS_URL"] || 'redis://localhost:6379')
  redis = Redis.new(:host => uri.host, :port => uri.port, :password => uri.password)

  set :data_store, Stoplight::DataStore::Redis.new(redis)
end
```

And then in routes.rb:

```
require 'stoplight_admin_app'

# only allow authenticated admin users access to stoplight web admin
authenticate :user, lambda { |u| u.admin? } do
    mount StoplightAdminApp => '/stoplight'
end
```

**Comment by tfausak** [comment]
We don't actually mount stoplight-admin in Rails, so I'm not sure about the best way to do this. If this worked for you, we can add it to the documentation.

**Comment by tfausak** [comment]
I think this is beyond the scope of our documentation. Stoplight Admin is a Sinatra app. It can be `mount`ed like any other Sinatra app.

**Comment by machadolab** [comment]
The issue I was pointing out is that it is not natively mountable directly as a sinatra app. You have to create a class that extends Sinatra::Base first. Most apps that are directly mountable as a sinatra app in rails have this mountable class provided by the gem, and don't require the application to do this themselves.

**Comment by tfausak** [comment]
Oh, I see what you mean. `Sinatra::StoplightAdmin` can't be mounted directly because it's not a Rack application. You have to wrap it in your own thing. 

Is there a sensible default we can provide? The data store must be set by the application, and that is going to vary. For instance, how would you use a Redis data store with this Rack application?

``` rb
class StoplightAdmin < Sinatra::Base
  register Sinatra::StoplightAdmin
  set :data_store, Stoplight::Light.default_data_store
end
```

**Comment by machadolab** [comment]
Yeah, that is why I suggested just documenting it!

**Comment by tfausak** [comment]
Fair enough!
