### ISSUE TITLE
Light color issue

### ISSUE THREAD

**Issue by grosscr** [orgsync/stoplight-admin#17]
With our configuration for our stoplights, we have a threshold of 5 configured for the number of errors to switch the light to red. However, I've noticed in the stoplight admin interface the light color changes to red in the GUI when it hits 3 errors instead of 5 (the stoplight is still functioning properly and waits for 2 more errors before preventing requests).

**Comment by tfausak** [comment]
Stoplights changed a while ago (https://github.com/orgsync/stoplight/pull/61) to not store the threshold in the data store. That means stoplight-admin can't do the right thing here because the information simply isn't available.

**Comment by grosscr** [comment]
Is that something that can be put back into stoplight? Or maybe make it configurable on the stoplight admin side? Maybe as an option when initializing the sentry application?

**Comment by tfausak** [comment]
You should be able to configure it by overriding the default threshold. I think setting `Stoplight::Default::THRESHOLD = 5` would suffice. 

The problem with making it configurable is that it can vary per stoplight. It can even vary per *run* of a stoplight! In practice that's probably a terrible idea, but the API does allow it.

``` rb
light = Stoplight('crazy') {}
(1 .. 3).each do |n|
  light.with_threshold(n).run
end
```

**Comment by grosscr** [comment]
Setting the default threshold when we initialized the sinatra app worked. Thanks for your help!
