### ISSUE TITLE
Publish 0.3.2

### ISSUE THREAD

**Issue by bschaeffer** [orgsync/stoplight-admin#21]
Will you publish the latest version to rubygems please 😄

**Comment by bschaeffer** [comment]
Ping!

**Comment by camdez** [comment]
@tfausak Can you handle this / or are you cool with me publishing this? (I haven't looked at this project in ages... 😅)

**Comment by tfausak** [comment]
I haven't looked at this in forever either. If you want to handle this, that's fine with me. Otherwise I'll hopefully spend some time this weekend getting automatic releases (via Travis) set up for both Stoplight and stoplight-admin.

**Comment by tfausak** [comment]
I manually pushed [stoplight-admin v0.3.2](https://rubygems.org/gems/stoplight-admin/versions/0.3.2) to RubyGems.

**Comment by bschaeffer** [comment]
Thanks!!!
